// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TourOperators
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap : IDisposable
    {
        
        #region Properties
        public UIHttpsravitejaPtsWebaWindow UIHttpsravitejaPtsWebaWindow
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebaWindow == null))
                {
                    this.mUIHttpsravitejaPtsWebaWindow = new UIHttpsravitejaPtsWebaWindow();
                }
                return this.mUIHttpsravitejaPtsWebaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsravitejaPtsWebaWindow mUIHttpsravitejaPtsWebaWindow;
        #endregion

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebaWindow : BrowserWindow
    {
        
        public UIHttpsravitejaPtsWebaWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://raviteja/PtsWeb/admin/signin";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://raviteja/PtsWeb/admin/signin");
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
            this.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/list");
            this.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsravitejaPtsWebaDocument UIHttpsravitejaPtsWebaDocument
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebaDocument == null))
                {
                    this.mUIHttpsravitejaPtsWebaDocument = new UIHttpsravitejaPtsWebaDocument(this);
                }
                return this.mUIHttpsravitejaPtsWebaDocument;
            }
        }
        
        public UIHttpsravitejaPtsWebADocument1 UIHttpsravitejaPtsWebADocument1
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebADocument1 == null))
                {
                    this.mUIHttpsravitejaPtsWebADocument1 = new UIHttpsravitejaPtsWebADocument1(this);
                }
                return this.mUIHttpsravitejaPtsWebADocument1;
            }
        }
        
        public UIHttpsravitejaPtsWebtDocument UIHttpsravitejaPtsWebtDocument
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebtDocument == null))
                {
                    this.mUIHttpsravitejaPtsWebtDocument = new UIHttpsravitejaPtsWebtDocument(this);
                }
                return this.mUIHttpsravitejaPtsWebtDocument;
            }
        }
        
        public UIHttpsravitejaPtsWebtDocument1 UIHttpsravitejaPtsWebtDocument1
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebtDocument1 == null))
                {
                    this.mUIHttpsravitejaPtsWebtDocument1 = new UIHttpsravitejaPtsWebtDocument1(this);
                }
                return this.mUIHttpsravitejaPtsWebtDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsravitejaPtsWebaDocument mUIHttpsravitejaPtsWebaDocument;
        
        private UIHttpsravitejaPtsWebADocument1 mUIHttpsravitejaPtsWebADocument1;
        
        private UIHttpsravitejaPtsWebtDocument mUIHttpsravitejaPtsWebtDocument;
        
        private UIHttpsravitejaPtsWebtDocument1 mUIHttpsravitejaPtsWebtDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebaDocument : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/admin/signin";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/admin/signin";
            this.WindowTitles.Add("https://raviteja/PtsWeb/admin/signin");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("https://raviteja/PtsWeb/admin/signin");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("https://raviteja/PtsWeb/admin/signin");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UISignInButton
        {
            get
            {
                if ((this.mUISignInButton == null))
                {
                    this.mUISignInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btn-signIn";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Sign In";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary pull-left";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary pull-left\" id=\"bt";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUISignInButton.WindowTitles.Add("https://raviteja/PtsWeb/admin/signin");
                    #endregion
                }
                return this.mUISignInButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUISignInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebADocument1 : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebADocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Admin";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Admin";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITourOperatorsHyperlink
        {
            get
            {
                if ((this.mUITourOperatorsHyperlink == null))
                {
                    this.mUITourOperatorsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITourOperatorsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITourOperatorsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITourOperatorsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITourOperatorsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Tour Operators";
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/touroperator/list";
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/touroperator/list";
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/PtsWeb/touroperator/list\" data-ho";
                    this.mUITourOperatorsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUITourOperatorsHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mUITourOperatorsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITourOperatorsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebtDocument : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebtDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/touroperator/list";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/touroperator/list";
            this.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/list");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITourOperatorHyperlink
        {
            get
            {
                if ((this.mUITourOperatorHyperlink == null))
                {
                    this.mUITourOperatorHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITourOperatorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITourOperatorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITourOperatorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITourOperatorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Tour Operator";
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/touroperator/Create";
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/touroperator/Create";
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-primary";
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" href=\"Create\"";
                    this.mUITourOperatorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "14";
                    this.mUITourOperatorHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/list");
                    #endregion
                }
                return this.mUITourOperatorHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITourOperatorHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebtDocument1 : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebtDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/touroperator/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/touroperator/Create";
            this.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "name";
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "name";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Name ";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"name\" class=\"form-control\" id=\"nam";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUINameEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        
        public HtmlEdit UITravelAgencyEdit
        {
            get
            {
                if ((this.mUITravelAgencyEdit == null))
                {
                    this.mUITravelAgencyEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITravelAgencyEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "travelagency";
                    this.mUITravelAgencyEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "travelagency";
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = " Travel Agency ";
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"travelagency\" class=\"form-control\"";
                    this.mUITravelAgencyEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUITravelAgencyEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUITravelAgencyEdit;
            }
        }
        
        public HtmlEdit UIRegistrationNumberEdit
        {
            get
            {
                if ((this.mUIRegistrationNumberEdit == null))
                {
                    this.mUIRegistrationNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIRegistrationNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "registrationnumber";
                    this.mUIRegistrationNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "registrationnumber";
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = " Registration Number ";
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"registrationnumber\" class=\"form-co";
                    this.mUIRegistrationNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIRegistrationNumberEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIRegistrationNumberEdit;
            }
        }
        
        public HtmlEdit UIMobileNumberEdit
        {
            get
            {
                if ((this.mUIMobileNumberEdit == null))
                {
                    this.mUIMobileNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIMobileNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "mobilenumber";
                    this.mUIMobileNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "mobilenumber";
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Mobile Number ";
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"mobilenumber\" class=\"form-control\"";
                    this.mUIMobileNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIMobileNumberEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIMobileNumberEdit;
            }
        }
        
        public HtmlEdit UIPhoneNumberEdit
        {
            get
            {
                if ((this.mUIPhoneNumberEdit == null))
                {
                    this.mUIPhoneNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhoneNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "phonenumber";
                    this.mUIPhoneNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "phonenumber";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Phone Number ";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"phonenumber\" class=\"form-control\" ";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIPhoneNumberEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIPhoneNumberEdit;
            }
        }
        
        public HtmlTextArea UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new HtmlTextArea(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "address";
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "address";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = " Address ";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"address\" class=\"form-control\" id=\"";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIAddressEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email ";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"email\" class=\"form-control\" id=\"em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIEmailEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIWebsiteEdit
        {
            get
            {
                if ((this.mUIWebsiteEdit == null))
                {
                    this.mUIWebsiteEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWebsiteEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "website";
                    this.mUIWebsiteEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "website";
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"website\" class=\"form-control\" id=\"";
                    this.mUIWebsiteEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIWebsiteEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIWebsiteEdit;
            }
        }
        
        public HtmlEdit UILocationNameEdit
        {
            get
            {
                if ((this.mUILocationNameEdit == null))
                {
                    this.mUILocationNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILocationNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "locationname";
                    this.mUILocationNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "locationname";
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Location Name ";
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"locationname\" class=\"form-control\"";
                    this.mUILocationNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUILocationNameEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUILocationNameEdit;
            }
        }
        
        public HtmlComboBox UIGradeComboBox
        {
            get
            {
                if ((this.mUIGradeComboBox == null))
                {
                    this.mUIGradeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIGradeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "grade";
                    this.mUIGradeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "grade";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Grade ";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "7";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"grade\" class=\"form-control\" id=\"gr";
                    this.mUIGradeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIGradeComboBox.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIGradeComboBox;
            }
        }
        
        public HtmlEdit UIRenewedUptoEdit
        {
            get
            {
                if ((this.mUIRenewedUptoEdit == null))
                {
                    this.mUIRenewedUptoEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIRenewedUptoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "renewedupto";
                    this.mUIRenewedUptoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "renewedupto";
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Renewed Upto ";
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"renewedupto\" class=\"form-control\" ";
                    this.mUIRenewedUptoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "9";
                    this.mUIRenewedUptoEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIRenewedUptoEdit;
            }
        }
        
        public HtmlTextArea UIRemarksEdit
        {
            get
            {
                if ((this.mUIRemarksEdit == null))
                {
                    this.mUIRemarksEdit = new HtmlTextArea(this);
                    #region Search Criteria
                    this.mUIRemarksEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "remarks";
                    this.mUIRemarksEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "remarks";
                    this.mUIRemarksEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = " Remarks ";
                    this.mUIRemarksEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIRemarksEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIRemarksEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"remarks\" class=\"form-control\" id=\"";
                    this.mUIRemarksEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIRemarksEdit.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUIRemarksEdit;
            }
        }
        
        public UIMshtmlHTMLInputElemeCustom UIMshtmlHTMLInputElemeCustom
        {
            get
            {
                if ((this.mUIMshtmlHTMLInputElemeCustom == null))
                {
                    this.mUIMshtmlHTMLInputElemeCustom = new UIMshtmlHTMLInputElemeCustom(this);
                }
                return this.mUIMshtmlHTMLInputElemeCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINameEdit;
        
        private HtmlEdit mUITravelAgencyEdit;
        
        private HtmlEdit mUIRegistrationNumberEdit;
        
        private HtmlEdit mUIMobileNumberEdit;
        
        private HtmlEdit mUIPhoneNumberEdit;
        
        private HtmlTextArea mUIAddressEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIWebsiteEdit;
        
        private HtmlEdit mUILocationNameEdit;
        
        private HtmlComboBox mUIGradeComboBox;
        
        private HtmlEdit mUIRenewedUptoEdit;
        
        private HtmlTextArea mUIRemarksEdit;
        
        private UIMshtmlHTMLInputElemeCustom mUIMshtmlHTMLInputElemeCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMshtmlHTMLInputElemeCustom : HtmlCustom
    {
        
        public UIMshtmlHTMLInputElemeCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "tourOperator";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "mshtml.HTMLInputElementClass";
            this.FilterProperties["Class"] = "form-horizontal bv-form";
            this.FilterProperties["ControlDefinition"] = "name=\"tourOperator\" class=\"form-horizont";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\" va";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "10";
                    this.mUICreateButton.WindowTitles.Add("https://raviteja/PtsWeb/touroperator/Create");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUICreateButton;
        #endregion
    }
}
