// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SapmleReports
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Location - Use 'LocationExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Location()
        {
            #region Variable Declarations
            HtmlDiv locationName = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame.UIRAPIssuanceReportDocument.LocationName;
            #endregion

            // Verify that the 'InnerText' property of 'Rangpo Check Post' pane equals 'Rangpo Check Post'
            Assert.AreEqual(this.LocationExpectedValues.LocationNameInnerText, locationName.InnerText, "Not found");
        }
        
        /// <summary>
        /// ScrollBar
        /// </summary>
        public void ScrollBar()
        {
            #region Variable Declarations
            HtmlDocument uIGovernmentofSikkimStDocument1 = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument1;
            #endregion

            // Move 'Government of Sikkim | State Permit Tracking Syste...' document
            Mouse.StartDragging(uIGovernmentofSikkimStDocument1, new Point(1361, 169));
            Mouse.StopDragging(uIGovernmentofSikkimStDocument1, 3, 207);
        }
        
        #region Properties
        public virtual LocationExpectedValues LocationExpectedValues
        {
            get
            {
                if ((this.mLocationExpectedValues == null))
                {
                    this.mLocationExpectedValues = new LocationExpectedValues();
                }
                return this.mLocationExpectedValues;
            }
        }
        
        public UIGovernmentofSikkimStWindow UIGovernmentofSikkimStWindow
        {
            get
            {
                if ((this.mUIGovernmentofSikkimStWindow == null))
                {
                    this.mUIGovernmentofSikkimStWindow = new UIGovernmentofSikkimStWindow();
                }
                return this.mUIGovernmentofSikkimStWindow;
            }
        }
        
        public UIHttpsravitejaPtsWebAWindow UIHttpsravitejaPtsWebAWindow
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebAWindow == null))
                {
                    this.mUIHttpsravitejaPtsWebAWindow = new UIHttpsravitejaPtsWebAWindow();
                }
                return this.mUIHttpsravitejaPtsWebAWindow;
            }
        }
        #endregion
        
        #region Fields
        private LocationExpectedValues mLocationExpectedValues;
        
        private UIGovernmentofSikkimStWindow mUIGovernmentofSikkimStWindow;
        
        private UIHttpsravitejaPtsWebAWindow mUIHttpsravitejaPtsWebAWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Location'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class LocationExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Rangpo Check Post' pane equals 'Rangpo Check Post'
        /// </summary>
        public string LocationNameInnerText = "Rangpo Check Post";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGovernmentofSikkimStWindow : BrowserWindow
    {
        
        public UIGovernmentofSikkimStWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Government of Sikkim | State Permit Tracking System";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGovernmentofSikkimStDocument UIGovernmentofSikkimStDocument
        {
            get
            {
                if ((this.mUIGovernmentofSikkimStDocument == null))
                {
                    this.mUIGovernmentofSikkimStDocument = new UIGovernmentofSikkimStDocument(this);
                }
                return this.mUIGovernmentofSikkimStDocument;
            }
        }
        
        public HtmlDocument UIGovernmentofSikkimStDocument1
        {
            get
            {
                if ((this.mUIGovernmentofSikkimStDocument1 == null))
                {
                    this.mUIGovernmentofSikkimStDocument1 = new HtmlDocument(this);
                    #region Search Criteria
                    this.mUIGovernmentofSikkimStDocument1.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
                    this.mUIGovernmentofSikkimStDocument1.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
                    this.mUIGovernmentofSikkimStDocument1.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
                    this.mUIGovernmentofSikkimStDocument1.FilterProperties[HtmlDocument.PropertyNames.Title] = "Government of Sikkim | State Permit Tracking System";
                    this.mUIGovernmentofSikkimStDocument1.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Reports/RAPIssuance.aspx";
                    this.mUIGovernmentofSikkimStDocument1.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://sikkimpts.azurewebsites.net/Reports/RAPIssuance.aspx";
                    this.mUIGovernmentofSikkimStDocument1.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIGovernmentofSikkimStDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIGovernmentofSikkimStDocument mUIGovernmentofSikkimStDocument;
        
        private HtmlDocument mUIGovernmentofSikkimStDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGovernmentofSikkimStDocument : HtmlDocument
    {
        
        public UIGovernmentofSikkimStDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Government of Sikkim | State Permit Tracking System";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Reports/RAPIssuance.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Reports/RAPIssuance.aspx";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIContentPlaceHolder1_Frame UIContentPlaceHolder1_Frame
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame == null))
                {
                    this.mUIContentPlaceHolder1_Frame = new UIContentPlaceHolder1_Frame(this);
                }
                return this.mUIContentPlaceHolder1_Frame;
            }
        }
        
        public UIContentPlaceHolder1_Frame1 UIContentPlaceHolder1_Frame1
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame1 == null))
                {
                    this.mUIContentPlaceHolder1_Frame1 = new UIContentPlaceHolder1_Frame1(this);
                }
                return this.mUIContentPlaceHolder1_Frame1;
            }
        }
        
        public UIContentPlaceHolder1_Frame2 UIContentPlaceHolder1_Frame2
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame2 == null))
                {
                    this.mUIContentPlaceHolder1_Frame2 = new UIContentPlaceHolder1_Frame2(this);
                }
                return this.mUIContentPlaceHolder1_Frame2;
            }
        }
        
        public HtmlComboBox UIDropDownListComboBox
        {
            get
            {
                if ((this.mUIDropDownListComboBox == null))
                {
                    this.mUIDropDownListComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIDropDownListComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1_ReportToolbar_ExportGr_FormatList_DropDownList";
                    this.mUIDropDownListComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$ReportViewer1$ReportToolbar$ExportGr$FormatList$DropDow" +
                        "nList";
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "7";
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$ReportVi";
                    this.mUIDropDownListComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIDropDownListComboBox.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIDropDownListComboBox;
            }
        }
        #endregion
        
        #region Fields
        private UIContentPlaceHolder1_Frame mUIContentPlaceHolder1_Frame;
        
        private UIContentPlaceHolder1_Frame1 mUIContentPlaceHolder1_Frame1;
        
        private UIContentPlaceHolder1_Frame2 mUIContentPlaceHolder1_Frame2;
        
        private HtmlComboBox mUIDropDownListComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=3e9ac9a9ac53488e9d7eef5955beaeea&opty" +
                "pe=Report&PageIndex=0&RenderID=1cb735d738c14a50af1b4991fe117393&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIRAPIssuanceReportDocument UIRAPIssuanceReportDocument
        {
            get
            {
                if ((this.mUIRAPIssuanceReportDocument == null))
                {
                    this.mUIRAPIssuanceReportDocument = new UIRAPIssuanceReportDocument(this);
                }
                return this.mUIRAPIssuanceReportDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIRAPIssuanceReportDocument mUIRAPIssuanceReportDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRAPIssuanceReportDocument : HtmlDocument
    {
        
        public UIRAPIssuanceReportDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "RAPIssuanceReport";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=3e9ac9a9ac53488e9d7ee" +
                "f5955beaeea&optype=Report&PageIndex=0&RenderID=1cb735d738c14a50af1b4991fe117393&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "pictureBox1 s15-";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"\" class=\"pictureBox1 s15-\" style=\"left: 0px; top: 0px; width: 106px; heigh" +
                        "t: 116px; overflow: hidden; position: absolute;\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "51";
                    this.mUIItemPane.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlDiv LocationName
        {
            get
            {
                if ((this.mLocationName == null))
                {
                    this.mLocationName = new HtmlDiv(this);
                    #region Search Criteria
                    this.mLocationName.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mLocationName.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mLocationName.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Rangpo Check Post";
                    this.mLocationName.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mLocationName.FilterProperties[HtmlDiv.PropertyNames.Class] = "textBox2 s5- action";
                    this.mLocationName.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"\" class=\"textBox2 s5- action\" style=\"left: 0px; top: 206px; width: 226px; " +
                        "height: 46px; overflow: hidden; position: absolute;\" onclick=\"javascript:Navigat" +
                        "eToReport(\'_115e7ad856694771bd7e28435477f459\');\"";
                    this.mLocationName.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mLocationName.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mLocationName;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        
        private HtmlDiv mLocationName;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame1 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=dff33aeaca0e4004ba21bdbe5d54e258&opty" +
                "pe=Report&PageIndex=0&RenderID=6178061c15b54f1599bb8f3fbe045aa4&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIRAPIssuanceDetailDocument UIRAPIssuanceDetailDocument
        {
            get
            {
                if ((this.mUIRAPIssuanceDetailDocument == null))
                {
                    this.mUIRAPIssuanceDetailDocument = new UIRAPIssuanceDetailDocument(this);
                }
                return this.mUIRAPIssuanceDetailDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIRAPIssuanceDetailDocument mUIRAPIssuanceDetailDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRAPIssuanceDetailDocument : HtmlDocument
    {
        
        public UIRAPIssuanceDetailDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "RAPIssuanceDetail";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=dff33aeaca0e4004ba21b" +
                "dbe5d54e258&optype=Report&PageIndex=0&RenderID=6178061c15b54f1599bb8f3fbe045aa4&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv TouristNames
        {
            get
            {
                if ((this.mTouristNames == null))
                {
                    this.mTouristNames = new HtmlDiv(this);
                    #region Search Criteria
                    this.mTouristNames.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mTouristNames.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mTouristNames.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "asdsad";
                    this.mTouristNames.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mTouristNames.FilterProperties[HtmlDiv.PropertyNames.Class] = "textBox5 s6- action";
                    this.mTouristNames.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"\" class=\"textBox5 s6- action\" style=\"left: 0px; top: 186px; width: 114px; " +
                        "height: 20px; overflow: hidden; position: absolute;\" onclick=\"javascript:Navigat" +
                        "eToReport(\'_57e2fd50d7b641b2a2ba654c78e2c8c1\');\"";
                    this.mTouristNames.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
                    this.mTouristNames.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mTouristNames;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mTouristNames;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame2 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=37ae332ab7794469ab9b3a30818e2f67&opty" +
                "pe=Report&PageIndex=0&RenderID=b4ed7c4cc7954de385287b00de47885d&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDocument UIRAPIssuanceDetailDocument
        {
            get
            {
                if ((this.mUIRAPIssuanceDetailDocument == null))
                {
                    this.mUIRAPIssuanceDetailDocument = new HtmlDocument(this);
                    #region Search Criteria
                    this.mUIRAPIssuanceDetailDocument.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
                    this.mUIRAPIssuanceDetailDocument.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
                    this.mUIRAPIssuanceDetailDocument.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
                    this.mUIRAPIssuanceDetailDocument.FilterProperties[HtmlDocument.PropertyNames.Title] = "RAPIssuanceDetail";
                    this.mUIRAPIssuanceDetailDocument.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
                    this.mUIRAPIssuanceDetailDocument.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=37ae332ab7794469ab9b3" +
                        "a30818e2f67&optype=Report&PageIndex=0&RenderID=b4ed7c4cc7954de385287b00de47885d&" +
                        "RenderingFormat=HTML5Interactive";
                    this.mUIRAPIssuanceDetailDocument.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIRAPIssuanceDetailDocument;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDocument mUIRAPIssuanceDetailDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebAWindow : BrowserWindow
    {
        
        public UIHttpsravitejaPtsWebAWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://raviteja/PtsWeb/Admin/SignIn";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsravitejaPtsWebADocument UIHttpsravitejaPtsWebADocument
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebADocument == null))
                {
                    this.mUIHttpsravitejaPtsWebADocument = new UIHttpsravitejaPtsWebADocument(this);
                }
                return this.mUIHttpsravitejaPtsWebADocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsravitejaPtsWebADocument mUIHttpsravitejaPtsWebADocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebADocument : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebADocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Admin/SignIn";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Admin/SignIn";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UISignInButton
        {
            get
            {
                if ((this.mUISignInButton == null))
                {
                    this.mUISignInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btn-signIn";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Sign In";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary pull-left";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary pull-left\" id=\"bt";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUISignInButton.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
                    #endregion
                }
                return this.mUISignInButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUISignInButton;
        #endregion
    }
}
