// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WebReports
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// MonthTotal - Use 'MonthTotalExpectedValues' to pass parameters into this method.
        /// </summary>
        public void MonthTotal()
        {
            #region Variable Declarations
            HtmlDiv totalMonthCount = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame.UIMonthlyTouristVisitiDocument.TotalMonthCount;
            #endregion

            // Verify that the 'InnerText' property of '51' pane equals '51'
            Assert.AreEqual(this.MonthTotalExpectedValues.TotalMonthCountInnerText, totalMonthCount.InnerText, "Total Not Found");
        }
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIItemHyperlink = this.UIHttpsravitejaPtsWebAWindow.UIHttpsravitejaPtsWebADocument1.UIItemHyperlink;
            HtmlHyperlink uILogoutHyperlink = this.UIHttpsravitejaPtsWebAWindow.UIHttpsravitejaPtsWebADocument1.UILogoutHyperlink;
            #endregion

            // Click link
            Mouse.Click(uIItemHyperlink, new Point(22, 29));

            // Click 'Logout' link
            Mouse.Click(uILogoutHyperlink, new Point(62, 12));
        }
        
        /// <summary>
        /// SinglePageCount - Use 'SinglePageCountExpectedValues' to pass parameters into this method.
        /// </summary>
        public void SinglePageCount()
        {
            #region Variable Declarations
            HtmlDiv singleCount = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame3.UIMonthlyTouristVisitiDocument.SingleCount;
            #endregion

            // Verify that the 'InnerText' property of '87' pane equals '87'
            Assert.AreEqual(this.SinglePageCountExpectedValues.SingleCountInnerText, singleCount.InnerText);
        }
        
        /// <summary>
        /// TotalMonthCount - Use 'TotalMonthCountExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TotalMonthCount()
        {
            #region Variable Declarations
            HtmlDiv totalCountMonthly = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame1.UIMonthlyTouristVisitiDocument.TotalCountMonthly;
            #endregion

            // Verify that the 'InnerText' property of '1' pane equals '1'
            Assert.AreEqual(this.TotalMonthCountExpectedValues.TotalCountMonthlyInnerText, totalCountMonthly.InnerText);
        }
        
        /// <summary>
        /// TotalTourists - Use 'TotalTouristsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TotalTourists()
        {
            #region Variable Declarations
            HtmlDiv totalCountSingleFrame = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame4.UIMonthlyTouristVisitiDocument.TotalCountSingleFrame;
            #endregion

            // Verify that the 'InnerText' property of '104' pane equals '104'
            Assert.AreEqual(this.TotalTouristsExpectedValues.TotalCountSingleFrameInnerText, totalCountSingleFrame.InnerText, "Total tourists not found");
        }
        
        /// <summary>
        /// ValidateTotalFrame2 - Use 'ValidateTotalFrame2ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateTotalFrame2()
        {
            #region Variable Declarations
            HtmlDiv totalMonthCount2 = this.UIGovernmentofSikkimStWindow.UIGovernmentofSikkimStDocument.UIContentPlaceHolder1_Frame2.UIMonthlyTouristVisitiDocument.TotalMonthCount2;
            #endregion

            // Verify that the 'InnerText' property of '495' pane equals '495'
            Assert.AreEqual(this.ValidateTotalFrame2ExpectedValues.TotalMonthCount2InnerText, totalMonthCount2.InnerText, "Total in second frame not found");
        }
        
        /// <summary>
        /// ValidateTotalRAP - Use 'ValidateTotalRAPExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateTotalRAP()
        {
            #region Variable Declarations
            HtmlCell totalRAP = this.UIHttpsravitejaPtsWebAWindow.UIHttpsravitejaPtsWebADocument1.UICountriesTable.TotalRAP;
            #endregion

            // Verify that the 'InnerText' property of '774' cell equals '774'
            Assert.AreEqual(this.ValidateTotalRAPExpectedValues.TotalRAPInnerText, totalRAP.InnerText, "Not Found");
        }
        
        #region Properties
        public virtual MonthTotalExpectedValues MonthTotalExpectedValues
        {
            get
            {
                if ((this.mMonthTotalExpectedValues == null))
                {
                    this.mMonthTotalExpectedValues = new MonthTotalExpectedValues();
                }
                return this.mMonthTotalExpectedValues;
            }
        }
        
        public virtual SinglePageCountExpectedValues SinglePageCountExpectedValues
        {
            get
            {
                if ((this.mSinglePageCountExpectedValues == null))
                {
                    this.mSinglePageCountExpectedValues = new SinglePageCountExpectedValues();
                }
                return this.mSinglePageCountExpectedValues;
            }
        }
        
        public virtual TotalMonthCountExpectedValues TotalMonthCountExpectedValues
        {
            get
            {
                if ((this.mTotalMonthCountExpectedValues == null))
                {
                    this.mTotalMonthCountExpectedValues = new TotalMonthCountExpectedValues();
                }
                return this.mTotalMonthCountExpectedValues;
            }
        }
        
        public virtual TotalTouristsExpectedValues TotalTouristsExpectedValues
        {
            get
            {
                if ((this.mTotalTouristsExpectedValues == null))
                {
                    this.mTotalTouristsExpectedValues = new TotalTouristsExpectedValues();
                }
                return this.mTotalTouristsExpectedValues;
            }
        }
        
        public virtual ValidateTotalFrame2ExpectedValues ValidateTotalFrame2ExpectedValues
        {
            get
            {
                if ((this.mValidateTotalFrame2ExpectedValues == null))
                {
                    this.mValidateTotalFrame2ExpectedValues = new ValidateTotalFrame2ExpectedValues();
                }
                return this.mValidateTotalFrame2ExpectedValues;
            }
        }
        
        public virtual ValidateTotalRAPExpectedValues ValidateTotalRAPExpectedValues
        {
            get
            {
                if ((this.mValidateTotalRAPExpectedValues == null))
                {
                    this.mValidateTotalRAPExpectedValues = new ValidateTotalRAPExpectedValues();
                }
                return this.mValidateTotalRAPExpectedValues;
            }
        }
        
        public UIHttpsravitejaPtsWebAWindow UIHttpsravitejaPtsWebAWindow
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebAWindow == null))
                {
                    this.mUIHttpsravitejaPtsWebAWindow = new UIHttpsravitejaPtsWebAWindow();
                }
                return this.mUIHttpsravitejaPtsWebAWindow;
            }
        }
        
        public UIGovernmentofSikkimStWindow UIGovernmentofSikkimStWindow
        {
            get
            {
                if ((this.mUIGovernmentofSikkimStWindow == null))
                {
                    this.mUIGovernmentofSikkimStWindow = new UIGovernmentofSikkimStWindow();
                }
                return this.mUIGovernmentofSikkimStWindow;
            }
        }
        #endregion
        
        #region Fields
        private MonthTotalExpectedValues mMonthTotalExpectedValues;
        
        private SinglePageCountExpectedValues mSinglePageCountExpectedValues;
        
        private TotalMonthCountExpectedValues mTotalMonthCountExpectedValues;
        
        private TotalTouristsExpectedValues mTotalTouristsExpectedValues;
        
        private ValidateTotalFrame2ExpectedValues mValidateTotalFrame2ExpectedValues;
        
        private ValidateTotalRAPExpectedValues mValidateTotalRAPExpectedValues;
        
        private UIHttpsravitejaPtsWebAWindow mUIHttpsravitejaPtsWebAWindow;
        
        private UIGovernmentofSikkimStWindow mUIGovernmentofSikkimStWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'MonthTotal'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class MonthTotalExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '51' pane equals '51'
        /// </summary>
        public string TotalMonthCountInnerText = "51";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SinglePageCount'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SinglePageCountExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '87' pane equals '87'
        /// </summary>
        public string SingleCountInnerText = "87";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TotalMonthCount'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TotalMonthCountExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '1' pane equals '1'
        /// </summary>
        public string TotalCountMonthlyInnerText = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TotalTourists'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TotalTouristsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '104' pane equals '104'
        /// </summary>
        public string TotalCountSingleFrameInnerText = "104";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateTotalFrame2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ValidateTotalFrame2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '495' pane equals '495'
        /// </summary>
        public string TotalMonthCount2InnerText = "495";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateTotalRAP'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ValidateTotalRAPExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '774' cell equals '774'
        /// </summary>
        public string TotalRAPInnerText = "774";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebAWindow : BrowserWindow
    {
        
        public UIHttpsravitejaPtsWebAWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://raviteja/PtsWeb/Admin/SignIn";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsravitejaPtsWebADocument UIHttpsravitejaPtsWebADocument
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebADocument == null))
                {
                    this.mUIHttpsravitejaPtsWebADocument = new UIHttpsravitejaPtsWebADocument(this);
                }
                return this.mUIHttpsravitejaPtsWebADocument;
            }
        }
        
        public UIHttpsravitejaPtsWebADocument1 UIHttpsravitejaPtsWebADocument1
        {
            get
            {
                if ((this.mUIHttpsravitejaPtsWebADocument1 == null))
                {
                    this.mUIHttpsravitejaPtsWebADocument1 = new UIHttpsravitejaPtsWebADocument1(this);
                }
                return this.mUIHttpsravitejaPtsWebADocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsravitejaPtsWebADocument mUIHttpsravitejaPtsWebADocument;
        
        private UIHttpsravitejaPtsWebADocument1 mUIHttpsravitejaPtsWebADocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebADocument : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebADocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Admin/SignIn";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Admin/SignIn";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlInputButton UISignInButton
        {
            get
            {
                if ((this.mUISignInButton == null))
                {
                    this.mUISignInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btn-signIn";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Sign In";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary pull-left";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary pull-left\" id=\"bt";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUISignInButton.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
                    #endregion
                }
                return this.mUISignInButton;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("https://raviteja/PtsWeb/Admin/SignIn");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlInputButton mUISignInButton;
        
        private HtmlEdit mUIPasswordEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHttpsravitejaPtsWebADocument1 : HtmlDocument
    {
        
        public UIHttpsravitejaPtsWebADocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Admin";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Admin";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
            #endregion
        }
        
        #region Properties
        public UICountriesTable UICountriesTable
        {
            get
            {
                if ((this.mUICountriesTable == null))
                {
                    this.mUICountriesTable = new UICountriesTable(this);
                }
                return this.mUICountriesTable;
            }
        }
        
        public HtmlHyperlink UITouristMonthlyVisitiHyperlink
        {
            get
            {
                if ((this.mUITouristMonthlyVisitiHyperlink == null))
                {
                    this.mUITouristMonthlyVisitiHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITouristMonthlyVisitiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITouristMonthlyVisitiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITouristMonthlyVisitiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITouristMonthlyVisitiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Tourist Monthly Visiting Report";
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/Reports/MonthlyVisitingReport.aspx";
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/Reports/MonthlyVisitingReport.aspx";
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/PtsWeb/Reports/MonthlyVisitingRep";
                    this.mUITouristMonthlyVisitiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUITouristMonthlyVisitiHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mUITouristMonthlyVisitiHyperlink;
            }
        }
        
        public HtmlHyperlink UIReportsHyperlink
        {
            get
            {
                if ((this.mUIReportsHyperlink == null))
                {
                    this.mUIReportsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIReportsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIReportsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIReportsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIReportsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Reports ";
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/Admin";
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/Admin#";
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle";
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle\" href=\"#\" data-to";
                    this.mUIReportsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIReportsHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mUIReportsHyperlink;
            }
        }
        
        public HtmlHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "  ";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/Admin";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/Admin#";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle\" href=\"#\" data-to";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "11";
                    this.mUIItemHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mUIItemHyperlink;
            }
        }
        
        public HtmlHyperlink UILogoutHyperlink
        {
            get
            {
                if ((this.mUILogoutHyperlink == null))
                {
                    this.mUILogoutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/PtsWeb/Admin/Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://raviteja/PtsWeb/Admin/Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/PtsWeb/Admin/Logout\"";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "13";
                    this.mUILogoutHyperlink.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mUILogoutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UICountriesTable mUICountriesTable;
        
        private HtmlHyperlink mUITouristMonthlyVisitiHyperlink;
        
        private HtmlHyperlink mUIReportsHyperlink;
        
        private HtmlHyperlink mUIItemHyperlink;
        
        private HtmlHyperlink mUILogoutHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICountriesTable : HtmlTable
    {
        
        public UICountriesTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "countries";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Location\r\n\r\nNumber of RAP\'s\r\n\r\n\r\nTotal R";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table table-striped table-bordered \" id=\"countries\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "10";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped table-bordered ";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
            #endregion
        }
        
        #region Properties
        public HtmlCell TotalRAP
        {
            get
            {
                if ((this.mTotalRAP == null))
                {
                    this.mTotalRAP = new HtmlCell(this);
                    #region Search Criteria
                    this.mTotalRAP.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mTotalRAP.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mTotalRAP.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mTotalRAP.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"text-center\" data-bind=\"text: m_Item2\"";
                    this.mTotalRAP.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "7";
                    this.mTotalRAP.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mTotalRAP.FilterProperties[HtmlCell.PropertyNames.Class] = "text-center";
                    this.mTotalRAP.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "14";
                    this.mTotalRAP.WindowTitles.Add("https://raviteja/PtsWeb/Admin");
                    #endregion
                }
                return this.mTotalRAP;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mTotalRAP;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGovernmentofSikkimStWindow : BrowserWindow
    {
        
        public UIGovernmentofSikkimStWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Government of Sikkim | State Permit Tracking System";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGovernmentofSikkimStDocument UIGovernmentofSikkimStDocument
        {
            get
            {
                if ((this.mUIGovernmentofSikkimStDocument == null))
                {
                    this.mUIGovernmentofSikkimStDocument = new UIGovernmentofSikkimStDocument(this);
                }
                return this.mUIGovernmentofSikkimStDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGovernmentofSikkimStDocument mUIGovernmentofSikkimStDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGovernmentofSikkimStDocument : HtmlDocument
    {
        
        public UIGovernmentofSikkimStDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Government of Sikkim | State Permit Tracking System";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Reports/MonthlyVisitingReport.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Reports/MonthlyVisitingReport.aspx";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDateInputEdit
        {
            get
            {
                if ((this.mUIDateInputEdit == null))
                {
                    this.mUIDateInputEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateInputEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_MonthYearPicker_dateInput";
                    this.mUIDateInputEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$MonthYearPicker$dateInput";
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "riTextBox riEnabled riHover";
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$MonthYea";
                    this.mUIDateInputEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUIDateInputEdit.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIDateInputEdit;
            }
        }
        
        public HtmlInputButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_SearchButton_input";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$SearchButton";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Search";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "rbDecorated";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$SearchBu";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "16";
                    this.mUISearchButton.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        
        public UIContentPlaceHolder1_Frame UIContentPlaceHolder1_Frame
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame == null))
                {
                    this.mUIContentPlaceHolder1_Frame = new UIContentPlaceHolder1_Frame(this);
                }
                return this.mUIContentPlaceHolder1_Frame;
            }
        }
        
        public UIContentPlaceHolder1_Table UIContentPlaceHolder1_Table
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Table == null))
                {
                    this.mUIContentPlaceHolder1_Table = new UIContentPlaceHolder1_Table(this);
                }
                return this.mUIContentPlaceHolder1_Table;
            }
        }
        
        public UIContentPlaceHolder1_Frame2 UIContentPlaceHolder1_Frame2
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame2 == null))
                {
                    this.mUIContentPlaceHolder1_Frame2 = new UIContentPlaceHolder1_Frame2(this);
                }
                return this.mUIContentPlaceHolder1_Frame2;
            }
        }
        
        public HtmlSpan UIItem2Pane
        {
            get
            {
                if ((this.mUIItem2Pane == null))
                {
                    this.mUIItem2Pane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItem2Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1_ReportToolbar_NavGr_CurrentPage_TotalPages";
                    this.mUIItem2Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem2Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "2";
                    this.mUIItem2Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem2Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIItem2Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"ContentPlaceHolder1_ReportViewer1_ReportToolbar_NavGr_CurrentPage_TotalPages\"" +
                        " style=\"cursor: default;\"";
                    this.mUIItem2Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIItem2Pane.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIItem2Pane;
            }
        }
        
        public UIContentPlaceHolder1_Frame1 UIContentPlaceHolder1_Frame1
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame1 == null))
                {
                    this.mUIContentPlaceHolder1_Frame1 = new UIContentPlaceHolder1_Frame1(this);
                }
                return this.mUIContentPlaceHolder1_Frame1;
            }
        }
        
        public UIContentPlaceHolder1_Frame3 UIContentPlaceHolder1_Frame3
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame3 == null))
                {
                    this.mUIContentPlaceHolder1_Frame3 = new UIContentPlaceHolder1_Frame3(this);
                }
                return this.mUIContentPlaceHolder1_Frame3;
            }
        }
        
        public UIContentPlaceHolder1_Frame4 UIContentPlaceHolder1_Frame4
        {
            get
            {
                if ((this.mUIContentPlaceHolder1_Frame4 == null))
                {
                    this.mUIContentPlaceHolder1_Frame4 = new UIContentPlaceHolder1_Frame4(this);
                }
                return this.mUIContentPlaceHolder1_Frame4;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDateInputEdit;
        
        private HtmlInputButton mUISearchButton;
        
        private UIContentPlaceHolder1_Frame mUIContentPlaceHolder1_Frame;
        
        private UIContentPlaceHolder1_Table mUIContentPlaceHolder1_Table;
        
        private UIContentPlaceHolder1_Frame2 mUIContentPlaceHolder1_Frame2;
        
        private HtmlSpan mUIItem2Pane;
        
        private UIContentPlaceHolder1_Frame1 mUIContentPlaceHolder1_Frame1;
        
        private UIContentPlaceHolder1_Frame3 mUIContentPlaceHolder1_Frame3;
        
        private UIContentPlaceHolder1_Frame4 mUIContentPlaceHolder1_Frame4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=f7d70c823fa24ffdb67957d4b8855f7b&opty" +
                "pe=Report&PageIndex=0&RenderID=5912b789d85b4b69969cebf4bcf4cdf6&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIMonthlyTouristVisitiDocument UIMonthlyTouristVisitiDocument
        {
            get
            {
                if ((this.mUIMonthlyTouristVisitiDocument == null))
                {
                    this.mUIMonthlyTouristVisitiDocument = new UIMonthlyTouristVisitiDocument(this);
                }
                return this.mUIMonthlyTouristVisitiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMonthlyTouristVisitiDocument mUIMonthlyTouristVisitiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMonthlyTouristVisitiDocument : HtmlDocument
    {
        
        public UIMonthlyTouristVisitiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MonthlyTouristVisiting";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=f7d70c823fa24ffdb6795" +
                "7d4b8855f7b&optype=Report&PageIndex=0&RenderID=5912b789d85b4b69969cebf4bcf4cdf6&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv TotalMonthCount
        {
            get
            {
                if ((this.mTotalMonthCount == null))
                {
                    this.mTotalMonthCount = new HtmlDiv(this);
                    #region Search Criteria
                    this.mTotalMonthCount.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mTotalMonthCount.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mTotalMonthCount.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "51";
                    this.mTotalMonthCount.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mTotalMonthCount.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mTotalMonthCount.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"left: 237px; top: 6px; white-space: pre; position: absolute; -ms-word-wrap" +
                        ": normal;\"";
                    this.mTotalMonthCount.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "134";
                    this.mTotalMonthCount.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mTotalMonthCount;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mTotalMonthCount;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Table : HtmlTable
    {
        
        public UIContentPlaceHolder1_Table(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1_ReportToolbar_NavGr_NextPage_Button";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"HoverButton\" id=\"ContentPlaceHolder1_ReportViewer1_ReportToolbar_NavGr_Nex" +
                "tPage_Button\" style=\"border-collapse: collapse;\" cellspacing=\"0\" cellpadding=\"0\"" +
                "";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "HoverButton";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "12";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"ImageButtonCell\" unselectable=\"on\"";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = "ImageButtonCell";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "53";
                    this.mUIItemCell.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame2 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=b1c04a438bf74c03a7a2fbfcc7e47184&opty" +
                "pe=Report&PageIndex=1&RenderID=f9bde69f444844d48cabbfd493636c53&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIMonthlyTouristVisitiDocument1 UIMonthlyTouristVisitiDocument
        {
            get
            {
                if ((this.mUIMonthlyTouristVisitiDocument == null))
                {
                    this.mUIMonthlyTouristVisitiDocument = new UIMonthlyTouristVisitiDocument1(this);
                }
                return this.mUIMonthlyTouristVisitiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMonthlyTouristVisitiDocument1 mUIMonthlyTouristVisitiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMonthlyTouristVisitiDocument1 : HtmlDocument
    {
        
        public UIMonthlyTouristVisitiDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MonthlyTouristVisiting";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=b1c04a438bf74c03a7a2f" +
                "bfcc7e47184&optype=Report&PageIndex=1&RenderID=f9bde69f444844d48cabbfd493636c53&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv TotalMonthCount2
        {
            get
            {
                if ((this.mTotalMonthCount2 == null))
                {
                    this.mTotalMonthCount2 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mTotalMonthCount2.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mTotalMonthCount2.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mTotalMonthCount2.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "495";
                    this.mTotalMonthCount2.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mTotalMonthCount2.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mTotalMonthCount2.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"left: 234px; top: 5px; white-space: pre; position: absolute; -ms-word-wrap" +
                        ": normal;\"";
                    this.mTotalMonthCount2.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
                    this.mTotalMonthCount2.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mTotalMonthCount2;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mTotalMonthCount2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame1 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=720f7229ca004bf5869b5f27d54dfafc&opty" +
                "pe=Report&PageIndex=0&RenderID=fd64baf327f745868ac5e27ffbb83212&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIMonthlyTouristVisitiDocument2 UIMonthlyTouristVisitiDocument
        {
            get
            {
                if ((this.mUIMonthlyTouristVisitiDocument == null))
                {
                    this.mUIMonthlyTouristVisitiDocument = new UIMonthlyTouristVisitiDocument2(this);
                }
                return this.mUIMonthlyTouristVisitiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMonthlyTouristVisitiDocument2 mUIMonthlyTouristVisitiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMonthlyTouristVisitiDocument2 : HtmlDocument
    {
        
        public UIMonthlyTouristVisitiDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MonthlyTouristVisiting";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=720f7229ca004bf5869b5" +
                "f27d54dfafc&optype=Report&PageIndex=0&RenderID=fd64baf327f745868ac5e27ffbb83212&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv TotalCountMonthly
        {
            get
            {
                if ((this.mTotalCountMonthly == null))
                {
                    this.mTotalCountMonthly = new HtmlDiv(this);
                    #region Search Criteria
                    this.mTotalCountMonthly.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mTotalCountMonthly.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mTotalCountMonthly.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1";
                    this.mTotalCountMonthly.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mTotalCountMonthly.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mTotalCountMonthly.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"left: 241px; top: 6px; white-space: pre; position: absolute; -ms-word-wrap" +
                        ": normal;\"";
                    this.mTotalCountMonthly.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "42";
                    this.mTotalCountMonthly.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mTotalCountMonthly;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mTotalCountMonthly;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame3 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=45558009331846658e651e4d3a4eb417&opty" +
                "pe=Report&PageIndex=0&RenderID=dd24536d1ab74eeba82dabc9f2462477&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIMonthlyTouristVisitiDocument3 UIMonthlyTouristVisitiDocument
        {
            get
            {
                if ((this.mUIMonthlyTouristVisitiDocument == null))
                {
                    this.mUIMonthlyTouristVisitiDocument = new UIMonthlyTouristVisitiDocument3(this);
                }
                return this.mUIMonthlyTouristVisitiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMonthlyTouristVisitiDocument3 mUIMonthlyTouristVisitiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMonthlyTouristVisitiDocument3 : HtmlDocument
    {
        
        public UIMonthlyTouristVisitiDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MonthlyTouristVisiting";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=45558009331846658e651" +
                "e4d3a4eb417&optype=Report&PageIndex=0&RenderID=dd24536d1ab74eeba82dabc9f2462477&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv SingleCount
        {
            get
            {
                if ((this.mSingleCount == null))
                {
                    this.mSingleCount = new HtmlDiv(this);
                    #region Search Criteria
                    this.mSingleCount.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mSingleCount.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mSingleCount.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "87";
                    this.mSingleCount.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mSingleCount.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mSingleCount.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"left: 237px; top: 6px; white-space: pre; position: absolute; -ms-word-wrap" +
                        ": normal;\"";
                    this.mSingleCount.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "178";
                    this.mSingleCount.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mSingleCount;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mSingleCount;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContentPlaceHolder1_Frame4 : HtmlIFrame
    {
        
        public UIContentPlaceHolder1_Frame4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ContentPlaceHolder1_ReportViewer1ReportFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/PtsWeb/Telerik.ReportViewer.axd?instanceID=baf11b88a77d458d87e08bffba130fb2&opty" +
                "pe=Report&PageIndex=0&RenderID=94b1f9c1c28544e9bc93d36857e6578e&RenderingFormat=" +
                "HTML5Interactive";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"0\" height=\"0\" id=\"ContentPlaceHol";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public UIMonthlyTouristVisitiDocument4 UIMonthlyTouristVisitiDocument
        {
            get
            {
                if ((this.mUIMonthlyTouristVisitiDocument == null))
                {
                    this.mUIMonthlyTouristVisitiDocument = new UIMonthlyTouristVisitiDocument4(this);
                }
                return this.mUIMonthlyTouristVisitiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMonthlyTouristVisitiDocument4 mUIMonthlyTouristVisitiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMonthlyTouristVisitiDocument4 : HtmlDocument
    {
        
        public UIMonthlyTouristVisitiDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MonthlyTouristVisiting";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/PtsWeb/Telerik.ReportViewer.axd";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://raviteja/PtsWeb/Telerik.ReportViewer.axd?instanceID=baf11b88a77d458d87e08" +
                "bffba130fb2&optype=Report&PageIndex=0&RenderID=94b1f9c1c28544e9bc93d36857e6578e&" +
                "RenderingFormat=HTML5Interactive";
            this.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
            #endregion
        }
        
        #region Properties
        public HtmlDiv TotalCountSingleFrame
        {
            get
            {
                if ((this.mTotalCountSingleFrame == null))
                {
                    this.mTotalCountSingleFrame = new HtmlDiv(this);
                    #region Search Criteria
                    this.mTotalCountSingleFrame.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mTotalCountSingleFrame.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mTotalCountSingleFrame.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "104";
                    this.mTotalCountSingleFrame.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mTotalCountSingleFrame.FilterProperties[HtmlDiv.PropertyNames.Class] = "textBox16 s11-";
                    this.mTotalCountSingleFrame.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"\" class=\"textBox16 s11-\" style=\"left: 279px; top: 875px; width: 487px; hei" +
                        "ght: 20px; overflow: hidden; position: absolute;\"";
                    this.mTotalCountSingleFrame.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "187";
                    this.mTotalCountSingleFrame.WindowTitles.Add("Government of Sikkim | State Permit Tracking System");
                    #endregion
                }
                return this.mTotalCountSingleFrame;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mTotalCountSingleFrame;
        #endregion
    }
}
